'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface TranslationRecord {
  [key: string]: string;
}

interface Translations {
  en: TranslationRecord;
  ar: TranslationRecord;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translations: Translations;
}

const defaultTranslations: Translations = {
  en: {
    // Common
    'app.title': 'khatak',
    'nav.home': 'Home',
    'nav.orders': 'Orders',
    'nav.tracking': 'Tracking',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'language.switch': 'العربية',
    
    // Homepage
    'homepage.subtitle': 'Fast and reliable shipping service for all your needs',
    'homepage.services.0.title': 'Express Delivery',
    'homepage.services.0.description': 'Same-day delivery service for urgent packages',
    'homepage.services.1.title': 'Package Tracking',
    'homepage.services.1.description': 'Real-time tracking of your shipments',
    'homepage.services.2.title': 'Secure Handling',
    'homepage.services.2.description': 'Your packages are always handled with care',
    'homepage.howItWorks.0.title': 'Create an order',
    'homepage.howItWorks.0.description': 'Fill in the shipping details',
    'homepage.howItWorks.1.title': 'Schedule pickup',
    'homepage.howItWorks.1.description': 'We\'ll collect your package',
    'homepage.howItWorks.2.title': 'Track delivery',
    'homepage.howItWorks.2.description': 'Monitor your shipment in real-time',
    'homepage.cta.title': 'Ready to Ship?',
    'homepage.cta.subtitle': 'Sign up now and send your first package today',
    'homepage.cta.buttonText': 'Get Started',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.forgotPassword': 'Forgot Password',
    'auth.email': 'Email',
    'auth.identifier': 'Email or Phone',
    'auth.identifierPlaceholder': 'Enter email or phone number',
    'auth.identifierHelp': 'You can login with either your email address or phone number',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember Me',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.registerHere': 'Register here',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.confirmPassword': 'Confirm Password',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.confirmPasswordPlaceholder': 'Confirm password',
    'auth.registerAsDriver': 'Register as a Driver',
    'auth.accountInformation': 'Account Information',
    'auth.firstNamePlaceholder': 'Enter first name',
    'auth.lastNamePlaceholder': 'Enter last name',
    'auth.phonePlaceholder': 'Enter phone number',
    'auth.passwordPlaceholder': 'Create a password',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.loginHere': 'Login here',
    'auth.registerAsCustomer': 'Looking to register as a customer?',
    'auth.completeRegistration': 'Complete Registration',
    'auth.registering': 'Registering...',
    'auth.fillAllFields': 'Please fill in all required fields',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.registrationFailed': 'Registration failed. Please try again.',
    
    // Admin
    'admin.title': 'Administrator',
    'admin.client': 'Client',
    'admin.driver': 'Driver',
    'admin.allOrders': 'All Orders',
    'admin.manageUsers': 'Manage Users',
    'admin.driverApprovals': 'Driver Approvals',
    'admin.paymentManagement': 'Payment Management',
    'admin.orderManagement': 'Order Management',
    'admin.searchOrders': 'Search by order #, customer, or address',
    'admin.search': 'Search',
    'admin.allStatuses': 'All Statuses',
    'admin.refresh': 'Refresh',
    'admin.orderNumber': 'Order #',
    'admin.customer': 'Customer',
    'admin.status': 'Status',
    'admin.pickupAddress': 'Pickup Address',
    'admin.deliveryAddress': 'Delivery Address',
    'admin.created': 'Created',
    'admin.amount': 'Amount',
    'admin.actions': 'Actions',
    'admin.details': 'Details',
    'admin.portal': 'Admin Portal',
    'admin.adminBadge': 'Admin',
    'admin.dashboard': 'Admin Dashboard',
    'admin.drivers': 'Drivers',
    'admin.customers': 'Customers',
    'admin.settings': 'Settings',
    'admin.noPermission': 'You don\'t have permission to access this page.',
    'admin.searchDrivers': 'Search by name or email',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.view': 'View',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.noDriverApplications': 'No driver applications found',
    'admin.approveDriver': 'Approve Driver',
    'admin.rejectDriver': 'Reject Driver',
    'admin.confirmApproveDriver': 'Are you sure you want to approve the driver application for',
    'admin.confirmRejectDriver': 'Are you sure you want to reject the driver application for',
    'admin.rejectionReason': 'Reason for Rejection',
    'admin.rejectionReasonPlaceholder': 'Please provide a reason for rejection...',
    'admin.driverId': 'Driver ID',
    
    // Users management page
    'admin.users.manageUsers': 'Manage Users',
    'admin.users.searchPlaceholder': 'Search by name or email',
    'admin.users.allRoles': 'All Roles',
    'admin.users.roleAdmin': 'Admins',
    'admin.users.roleClient': 'Clients',
    'admin.users.roleDriver': 'Drivers',
    'admin.users.roleADMIN': 'Admin',
    'admin.users.roleCLIENT': 'Client',
    'admin.users.roleDRIVER': 'Driver',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Inactive',
    'admin.users.never': 'Never',
    'admin.users.name': 'Name',
    'admin.users.email': 'Email',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.joined': 'Joined',
    'admin.users.lastActive': 'Last Active',
    'admin.users.resetPwd': 'Reset Password',
    'admin.users.deactivate': 'Deactivate',
    'admin.users.activate': 'Activate',
    'admin.users.noUsersFound': 'No users found matching your criteria',
    'admin.users.userDetails': 'User Details',
    'admin.users.basicInfo': 'Basic Information',
    'admin.users.accountDetails': 'Account Details',
    'admin.users.driverProfile': 'Driver Profile',
    'admin.users.driverInfo': 'Driver Information',
    'admin.users.phone': 'Phone',
    'admin.users.notProvided': 'Not provided',
    'admin.users.totalOrders': 'Total Orders',
    'admin.users.documents': 'Documents',
    'admin.users.clickToEnlarge': 'Click to enlarge',
    'admin.users.viewFullSize': 'View Full Size',
    'admin.users.noDocumentsAvailable': 'No documents available',
    'admin.users.noDriverProfileInfo': 'No driver profile information available',
    'admin.users.resetPassword': 'Reset Password',
    'admin.users.resetPasswordConfirm': 'Are you sure you want to reset the password for',
    'admin.users.resetPasswordWarning': 'A temporary password will be created and displayed here',
    'admin.users.confirmReset': 'Reset Password',
    'admin.users.noEmailError': 'No email address provided',
    'admin.users.passwordResetSuccess': 'Password reset successfully',
    'admin.users.passwordResetFailed': 'Failed to reset password',
    'admin.users.tempPassword': 'Temporary Password',
    'admin.users.passwordWarning': 'Share this temporary password with the user securely',
    'admin.users.approvalStatus': 'Approval Status',
    'admin.users.pending': 'Pending',
    'admin.users.editUser': 'Edit User',
    'admin.edit': 'Edit',
    'admin.users.editInfo': 'Edit Personal Information',
    'admin.users.addressInfo': 'Address Information',
    'admin.users.streetAddress': 'Street Address',
    'admin.users.city': 'City',
    'admin.users.state': 'State/Province',
    'admin.users.zipCode': 'Zip/Postal Code',
    'admin.users.country': 'Country',
    'admin.users.saveChanges': 'Save Changes',
    'admin.users.userUpdated': 'User updated successfully',
    'admin.users.updateFailed': 'Failed to update user',
    'admin.users.fieldRequired': 'This field is required',
    
    // Driver
    'driver.becomeDriver': 'Want to become a driver?',
    'driver.earnMoney': 'Earn money by delivering packages',
    'driver.registration': 'Driver Registration',
    'driver.vehicle': 'Vehicle',
    'driver.applicationDate': 'Application Date',
    'driver.applicationDetails': 'Driver Application Details',
    'driver.personalInfo': 'Personal Information',
    'driver.vehicleInfo': 'Vehicle Information',
    'driver.make': 'Make',
    'driver.model': 'Model',
    'driver.year': 'Year',
    'driver.color': 'Color',
    'driver.licensePlate': 'License Plate',
    'driver.licenseInfo': 'License Information',
    'driver.licenseNumber': 'License Number',
    'driver.expiryDate': 'Expiry Date',
    'driver.documents': 'Documents',
    'driver.license': 'Driver\'s License',
    'driver.vehicleRegistration': 'Vehicle Registration',
    'driver.insurance': 'Insurance',
    'driver.backgroundCheck': 'Background Check',
    'driver.noDocuments': 'No documents available',
    'driver.driverPhotos': 'Driver Photos (Selfie/Portrait)',
    'driver.carPhotos': 'Car Photos',
    'driver.uploadDriverPhoto': 'Upload Driver Photo',
    'driver.uploadCarPhotos': 'Upload Car Photos',
    'driver.uploadLicense': 'Upload License',
    'driver.photos': 'photos',
    'driver.photoInstructions': 'Please provide a clear photo of your face (like a selfie) with good lighting.',
    'driver.carPhotoInstructions': 'Please provide photos of your car from different angles (front, back, and sides).',
    'driver.licenseInstructions': 'Please provide a clear photo or scan of your valid driver\'s license.',
    'driver.uploadingDocuments': 'Uploading documents...',
    'driver.maxDriverPhotosError': 'Maximum 2 driver photos allowed',
    'driver.maxCarPhotosError': 'Maximum 4 car photos allowed',
    'driver.plateNumberRequired': 'License plate number is required',
    'driver.licenseRequired': 'A copy of your driver license is required',
    'driver.carPhotoRequired': 'At least one car photo is required',
    'driver.driverPhotoRequired': 'At least one driver photo is required',
    'driver.uploadLicenseError': 'Failed to upload license document',
    'driver.uploadCarPhotoError': 'Failed to upload car photo',
    'driver.uploadDriverPhotoError': 'Failed to upload driver photo',
    'driver.uploadInsuranceError': 'Failed to upload insurance document',
    'driver.uploadError': 'Failed to upload documents. Please try again.',
    'driver.licensePlatePlaceholder': 'Enter license plate number',
    'driver.makePlaceholder': 'e.g. Toyota, Honda',
    'driver.modelPlaceholder': 'e.g. Camry, Civic',
    'driver.yearPlaceholder': 'e.g. 2020',
    'driver.colorPlaceholder': 'e.g. Black, White',
    
    // Admin payments
    'admin.payments.totalCommission': 'Total Commission',
    'admin.payments.pendingCommission': 'Pending Commission',
    'admin.payments.rejectedPayments': 'Rejected Payments',
    'admin.payments.totalDrivers': 'Total Drivers',
    'admin.payments.topDriversByCommission': 'Top Drivers by Commission Paid',
    'admin.payments.driver': 'Driver',
    'admin.payments.paidCommission': 'Paid Commission',
    'admin.payments.totalPayments': 'Total Payments',
    'admin.payments.noDriverData': 'No payment data available',
    'admin.payments.paymentsTab': 'Payment Management',
    'admin.payments.bankAccountsTab': 'Bank Accounts',
    'admin.payments.paymentId': 'Payment ID',
    'admin.payments.amount': 'Amount',
    'admin.payments.status': 'Status',
    'admin.payments.date': 'Date',
    'admin.payments.actions': 'Actions',
    'admin.payments.confirmed': 'Confirmed',
    'admin.payments.pending': 'Pending',
    'admin.payments.rejected': 'Rejected',
    'admin.payments.confirm': 'Confirm',
    'admin.payments.reject': 'Reject',
    'admin.payments.unknownDriver': 'Unknown Driver',
    'admin.payments.noPaymentsFound': 'No payments found',
    'admin.payments.management': 'Payment Management',
    'admin.payments.totalPending': 'Total Pending',
    'admin.payments.totalConfirmed': 'Total Confirmed',
    'admin.payments.totalRejected': 'Total Rejected',
    'admin.payments.reportedIssues': 'Reported Issues',
    'admin.payments.requiresAttention': 'Requires attention',
    'admin.payments.payments': 'payments',
    'admin.payments.addBankAccount': 'Add Bank Account',
    'admin.payments.noPendingPayments': 'No pending payments',
    'admin.payments.bankAccount': 'Bank Account',
    'admin.payments.noBankAccount': 'No bank account',
    'admin.payments.noConfirmedPayments': 'No confirmed payments',
    'admin.payments.confirmedBy': 'Confirmed By',
    'admin.system': 'System',
    'admin.payments.noRejectedPayments': 'No rejected payments',
    'admin.payments.rejectionReason': 'Rejection Reason',
    'admin.payments.noReasonProvided': 'No reason provided',
    'admin.payments.rejectedBy': 'Rejected By',
    'admin.payments.issues': 'Issues',
    'admin.payments.noReportedIssues': 'No reported issues',
    'admin.payments.issue': 'Issue',
    'admin.payments.issueReported': 'Issue reported',
    'admin.payments.bankAccounts': 'Bank Accounts',
    'admin.payments.noBankAccounts': 'No bank accounts',
    'admin.payments.bankName': 'Bank Name',
    'admin.payments.accountName': 'Account Name',
    'admin.payments.accountNumber': 'Account Number',
    'admin.payments.sortCode': 'Sort Code',
    'admin.payments.description': 'Description',
    'admin.payments.active': 'Active',
    'admin.payments.inactive': 'Inactive',
    'admin.payments.paymentDetails': 'Payment Details',
    'admin.payments.paymentInfo': 'Payment Information',
    'admin.payments.id': 'ID',
    'admin.payments.notes': 'Notes',
    'admin.payments.driverInfo': 'Driver Information',
    'admin.payments.name': 'Name',
    'admin.payments.email': 'Email',
    'admin.payments.phone': 'Phone',
    'admin.notProvided': 'Not provided',
    'admin.payments.driverNotFound': 'Driver not found',
    'admin.payments.bankAccountInfo': 'Bank Account Information',
    'admin.payments.noBankAccountLinked': 'No bank account linked',
    'admin.payments.paymentActions': 'Payment Actions',
    'admin.payments.confirmPayment': 'Confirm Payment',
    'admin.payments.rejectPayment': 'Reject Payment',
    'admin.payments.rejectionReasonPlaceholder': 'Enter reason for rejection',
    'admin.payments.rejectionNoteRequired': 'A rejection note is required',
    'admin.payments.paymentReceipt': 'Payment Receipt',
    'admin.payments.editBankAccount': 'Edit Bank Account',
    'admin.payments.isActive': 'Is Active',
    'admin.payments.defaultRejectionNote': 'Payment rejected by administrator',
    'admin.payments.bankSaveError': 'Failed to save bank account',
    'admin.payments.confirmDeleteBank': 'Are you sure you want to delete this bank account?',
    'admin.payments.bankDeleteError': 'Failed to delete bank account',
    
    // General
    'general.notApplicable': 'N/A',
    'general.clickToEnlarge': 'Click to enlarge',
    'general.viewFullSize': 'View Full Size',
    'general.currency': 'Saudi Riyal',
    
    // Orders
    'orders.title': 'My Orders',
    'orders.new': 'Create New Order',
    'orders.track': 'Track Order',
    'orders.details': 'Order Details',
    'orders.available': 'Available Orders',
    'orders.current': 'Current Orders',
    'orders.history': 'Orders History',
    'orders.viewCurrentOrders': 'View Current Orders',
    'orders.haveActiveOrder': 'You Have an Active Order',
    'orders.oneOrderAtTime': 'You can only accept one order at a time. Please complete or cancel your current order before accepting a new one.',
    'orders.lookingToAccept': 'Looking for orders to accept?',
    'orders.pendingDescription': 'All orders with PENDING status are shown here. Once you accept an order, it will appear in your Current Orders.',
    'orders.orderInfo': 'Order Information',
    'orders.created': 'Created',
    'orders.updated': 'Updated',
    'orders.estimatedDelivery': 'Estimated Delivery',
    'orders.yes': 'Yes',
    'orders.no': 'No',
    'orders.viewOnMap': 'View on Map',
    'orders.client': 'Client',
    'orders.driver': 'Driver',
    'orders.name': 'Name',
    'orders.email': 'Email',
    'orders.phone': 'Phone',
    'orders.noDriverAssigned': 'No driver assigned yet',
    'orders.error': 'Error!',
    'orders.retry': 'Retry',
    'orders.notFound': 'Order Not Found',
    'orders.noPermission': 'The requested order could not be found or you don\'t have permission to view it.',
    'orders.missingOrderId': 'Order ID is missing',
    'orders.fetchDetailsFailed': 'Failed to fetch order details',
    'orders.acceptSuccess': 'Order accepted successfully',
    'orders.acceptFailed': 'Failed to accept order',
    'orders.pickedUpSuccess': 'Order marked as picked up',
    'orders.deliveredSuccess': 'Order marked as delivered',
    'orders.updateStatusFailed': 'Failed to update order status',
    'orders.cancelSuccess': 'Order cancelled successfully',
    'orders.country': 'Country',
    'orders.loadingAvailable': 'Loading available orders...',
    'orders.noAvailable': 'No Available Orders',
    'orders.checkBackLater': 'There are currently no available orders to accept. Please check back later.',
    'orders.orderNumber': 'Order #',
    'orders.acceptOrder': 'Accept Order',
    'orders.acceptingOrder': 'Accepting...',
    'orders.weightUnit': 'lbs',
    'orders.distanceUnit': 'miles',
    'orders.distance': 'Distance',
    'orders.timeUnit': 'mins',
    'orders.estimatedTime': 'Est. Time',
    'orders.fragileWarning': 'Fragile - Handle with care',
    'orders.noActiveOrders': 'No Active Orders',
    'orders.noDriverOrders': "You don't have any assigned orders at the moment. Check the Available Orders page to accept new orders.",
    'orders.noClientOrders': "You don't have any active orders at the moment.",
    'orders.findAvailable': 'Find Available Orders',
    'orders.refreshing': 'Refreshing...',
    'orders.trackingNumber': 'Tracking Number',
    'orders.status': 'Status',
    'orders.actions': 'Actions',
    'orders.price': 'Price',
    'orders.createdAt': 'Created At',
    'orders.completedDate': 'Completed Date',
    'orders.noCompletedOrders': 'No Completed Orders',
    'orders.noOrdersInHistory': "You don't have any completed orders in your history.",
    'orders.markAsPickedUp': 'Mark as Picked Up',
    'orders.startTransit': 'Start Transit',
    'orders.markAsDelivered': 'Mark as Delivered',
    'orders.cancelOrder': 'Cancel Order',
    'orders.confirmClientCancel': 'Are you sure you want to cancel this order? This action cannot be undone.',
    'orders.confirmDriverCancel': 'Are you sure you want to cancel this delivery? This will make the order available for other drivers.',
    'orders.confirmAdminCancel': 'Are you sure you want to cancel this order? This action cannot be undone.',
    'orders.clientCancelSuccess': 'Order cancelled successfully',
    'orders.driverCancelSuccess': 'Delivery cancelled successfully',
    'orders.adminCancelSuccess': 'Order cancelled successfully',
    'orders.cancelFailed': 'Failed to cancel order',
    'orders.cancelError': 'Failed to cancel order. Please try again.',
    
    // Payments
    'payment.history': 'Payment History',
    'payment.history.loading': 'Loading payment history...',
    'payment.history.noHistory': 'No Payment History',
    'payment.history.noRecords': 'You don\'t have any payment records yet.',
    'payment.history.viewReceipt': 'View Receipt',
    'payment.confirmation': 'تأكيد الدفع',
    'payment.confirmation.bankAccounts': 'الحسابات المصرفية',
    'payment.confirmation.noBankAccounts': 'لا توجد حسابات مصرفية متاحة. يرجى الاتصال بالمسؤول.',
    'payment.confirmation.pendingPayments': 'المدفوعات المعلقة',
    'payment.confirmation.loadingPayments': 'جاري تحميل المدفوعات...',
    'payment.confirmation.noPendingPayments': 'لا توجد مدفوعات معلقة',
    'payment.confirmation.noPaymentsDescription': 'لا توجد حاليا مدفوعات تحتاج إلى تأكيد.',
    'payment.confirmation.order': 'الطلب',
    'payment.confirmation.method': 'طريقة الدفع',
    'payment.confirmation.reference': 'المرجع',
    'payment.confirmation.receipt': 'إيصال',
    'payment.confirmation.ref': 'مرجع',
    'payment.confirmation.verifyMessage': 'يرجى تأكيد أن هذا الدفع تمت معالجته بشكل صحيح أو الإبلاغ عن مشكلة إذا كانت هناك مشكلة.',
    'payment.confirmation.reportIssue': 'الإبلاغ عن مشكلة',
    'payment.confirmation.confirm': 'تأكيد الدفع',
    'payment.confirmation.success': 'تم تأكيد الدفع بنجاح!',
    'payment.confirmation.failed': 'فشل تأكيد الدفع. يرجى المحاولة مرة أخرى.',
    'payment.confirmation.reportedIssue': 'تم الإبلاغ عن مشكلة من قبل السائق',
    'payment.confirmation.reportFailed': 'فشل الإبلاغ عن مشكلة الدفع. يرجى المحاولة مرة أخرى.',
    'payment.confirmation.issueReported': 'تم إبلاغ المسؤول عن مشكلة الدفع',
    'button.processing': 'جاري المعالجة...',
    
    // User
    'user.profile': 'Profile',
    'user.notifications': 'Notifications',
    
    // Notifications page
    'notifications.title': 'Your Notifications',
    'notifications.refresh': 'Refresh',
    'notifications.markSelected': 'Mark Selected as Read',
    'notifications.filter': 'Filter:',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.type': 'Type:',
    'notifications.empty': 'No notifications found matching your filters.',
    'notifications.loading': 'Loading...',
    'notifications.showing': 'Showing {0} notification(s)',
    'notifications.select': 'Select',
    'notifications.time': 'Time',
    'notifications.details': 'Details',
    'notifications': 'Notifications',
    'noNotifications': 'No notifications',
    
    // Notification types and common messages
    'notification.order.assigned': 'You have been assigned to order #{0}',
    'notification.order.delivered': 'Order #{0} has been delivered',
    'notification.order.cancelled': 'Order #{0} has been cancelled',
    'notification.order.status_update.title': 'Order Status Updated',
    'notification.order.status_update.accepted': 'Driver {0} has accepted your order #{1}',
    'notification.order.status_update.picked_up': 'Driver {0} has picked up your order #{1}',
    'notification.order.status_update.in_transit': 'Your order #{0} is now in transit',
    'notification.payment.received': 'Payment of {0} ريال سعودي has been received',
    'notification.payment.confirmed': 'Your payment for order #{0} has been confirmed',
    'notification.payment.rejected': 'Your payment for order #{0} has been rejected',
    'notification.account.welcome': 'Welcome to Katakksa! Your account has been created successfully.',
    'notification.system.maintenance': 'System maintenance scheduled for {0}',
    
    // Buttons
    'button.submit': 'Submit',
    'button.cancel': 'Cancel',
    'button.save': 'Save',
    'button.update': 'Update',
    'button.loading': 'Loading...',
    'button.close': 'Close',
    'button.next': 'Next',
    'button.back': 'Back',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.title': 'Dashboard',
    'dashboard.welcomeMessage': 'Welcome',
    'dashboard.summary': 'View your order statistics and recent activities below.',
    'dashboard.user': 'User',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.activeOrders': 'Active Orders',
    'dashboard.completedOrders': 'Completed Orders',
    'dashboard.cancelledOrders': 'Cancelled Orders',
    'dashboard.pendingOrders': 'Pending Orders',
    'dashboard.inTransit': 'In Transit',
    'dashboard.delivered': 'Delivered',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.noRecentOrders': 'No recent orders found',
    'dashboard.noOrders': 'No orders found',
    'dashboard.trackingNumber': 'Tracking Number',
    'dashboard.orderID': 'Order ID',
    'dashboard.date': 'Date',
    'dashboard.status': 'Status',
    'dashboard.destination': 'Destination',
    'dashboard.createdAt': 'Created At',
    'dashboard.actions': 'Actions',
    'dashboard.viewDetails': 'View Details',
    'dashboard.orderStatus.PENDING': 'Pending',
    'dashboard.orderStatus.IN_TRANSIT': 'In Transit',
    'dashboard.orderStatus.DELIVERED': 'Delivered',
    'dashboard.orderStatus.CANCELLED': 'Cancelled',
    'dashboard.orderStatus.ACCEPTED': 'Accepted',
    'dashboard.orderStatus.PICKED_UP': 'Picked Up',
    
    // Profile
    'profile.editProfile': 'Edit Profile',
    'profile.saving': 'Saving...',
    'profile.updateSuccess': 'Profile updated successfully',
    
    // Order Form
    'orders.fillPickupFields': 'Please fill in all required pickup address fields',
    'orders.fillDeliveryFields': 'Please fill in all required delivery address fields including recipient mobile number',
    'orders.invalidMobile': 'Please enter a valid recipient mobile number',
    'orders.fillPackageDetails': 'Please fill in package weight and price',
    'orders.invalidPrice': 'Please enter a valid price greater than zero',
    'orders.pickup': 'Pickup',
    'orders.delivery': 'Delivery',
    'orders.package': 'Package',
    'orders.location': 'Location',
    'orders.pickupAddress': 'Pickup Address',
    'orders.deliveryAddress': 'Delivery Address',
    'orders.street': 'Street Address',
    'orders.city': 'City',
    'orders.state': 'State',
    'orders.recipientMobile': 'Recipient Mobile Number',
    'orders.packageDetails': 'Package Details & Price',
    'orders.weight': 'Package Weight (lbs)',
    'orders.dimensions': 'Dimensions (LxWxH inches)',
    'orders.description': 'Package Description',
    'orders.fragile': 'This package is fragile',
    'orders.enterPrice': 'Enter Price',
    'orders.deliveryLocation': 'Delivery Location',
    'orders.selectLocation': 'Please select the exact delivery location on the map',
    'orders.mapPlaceholder': 'Map will be displayed here',
    'orders.mapIntegration': '(Google Maps or similar service integration required)',
    'orders.selectedLocation': 'Selected Location',
    'orders.noLocationSelectedYet': 'No location selected yet',
    'orders.useDeliveryAddress': 'Use Delivery Address',
    'orders.simulateMapSelection': 'Simulate Map Selection',
    'orders.note': 'Note',
    'orders.realImplementation': 'In the real implementation, this would be replaced with an interactive map where users can precisely select the delivery location.',
    'orders.newOrderDescription': 'Fill out the form to create a new shipping order',
    'orders.creating': 'Creating Order...',
    'orders.createOrder': 'Create Order',
    'orders.createNewOrder': 'Create New Order',
    'orders.processing': 'Processing...',
    'orders.next': 'Next',
    'orders.previous': 'Previous',
    
    // Pagination
    'pagination.previous': 'السابق',
    'pagination.next': 'التالي',
    'pagination.noOrders': 'لم يتم العثور على طلبات مطابقة لمعاييرك',
    
    // Admin Dashboard
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'active',
    'admin.totalOrdersCount': 'Total Orders',
    'admin.totalCompleted': 'completed',
    'admin.totalRevenue': 'Total Revenue',
    'admin.revenueGrowth': 'growth',
    'admin.pendingDriversCount': 'Pending Drivers',
    'admin.awaitingApproval': 'Awaiting approval',
    'admin.viewAllUsers': 'View All Users',
    'admin.viewAllOrders': 'View All Orders',
    'admin.revenueDetails': 'Revenue Details',
    'admin.viewPendingDrivers': 'View Pending Drivers',
    'admin.recentOrdersList': 'Recent Orders',
    'admin.recentUsers': 'Recent Users',
    'admin.noRecentOrders': 'No recent orders found',
    'admin.noRecentUsers': 'No recent users found',
    'admin.orderNum': 'Order #',
    'admin.customerName': 'Customer',
    'admin.dateField': 'Date',
    'admin.statusField': 'Status',
    'admin.amountField': 'Amount',
    'admin.nameField': 'Name',
    'admin.emailField': 'Email',
    'admin.roleField': 'Role',
    'admin.joinedDate': 'Joined',
    'admin.lastActive': 'Last Active',
    'admin.viewAll': 'View All',
    'admin.never': 'Never',
    
    // Logout
    'logout.confirmMessage': 'Are you sure you want to log out?',
    
    // Common Loading and Error Messages
    'loading.message': 'Loading...',
    'error.failed': 'Failed to load data. Please try again.',
    'error.auth': 'User data incomplete. Please login again.',
    'button.search': 'Search',
    'button.clear': 'Clear',
    'button.filter': 'Filter',
    'button.resetFilters': 'Reset Filters',
    'button.delete': 'Delete',
    'button.confirm': 'Confirm',
    'button.reject': 'Reject',
    'button.approve': 'Approve',
    'button.previous': 'Previous',
    'button.refresh': 'Refresh',
    
    // Driver
    'driver.verificationPending': 'Verification Pending',
    'driver.verificationPendingMessage': 'Thank you for registering as a driver with our platform. Your application has been submitted and is now pending verification.',
    'driver.verificationReviewMessage': 'Our admin team will review your information and documents. This typically takes 1-3 business days. You will receive an email notification once your account has been approved or if we need additional information.',
    'driver.whatsNext': 'What happens next?',
    'driver.nextStep1': 'Your driver registration will be reviewed by our admin team',
    'driver.nextStep2': 'We may contact you for additional information if needed',
    'driver.nextStep3': 'Once approved, you\'ll receive an email with your account details',
    'driver.nextStep4': 'You can then log in and start accepting delivery assignments',
    'driver.goToLogin': 'Go to Login Page',
    'driver.returnToHome': 'Return to Home',
    'driver.needHelp': 'Need help?',
    'driver.contactSupport': 'Contact Support',
  },
  ar: {
    // Common
    'app.title': 'خطك',
    'nav.home': 'الرئيسية',
    'nav.orders': 'الطلبات',
    'nav.tracking': 'تتبع',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.profile': 'الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'language.switch': 'English',
    
    // Homepage
    'homepage.subtitle': 'خدمة شحن سريعة وموثوقة لجميع احتياجاتك',
    'homepage.services.0.title': 'توصيل سريع',
    'homepage.services.0.description': 'خدمة توصيل في نفس اليوم للطرود العاجلة',
    'homepage.services.1.title': 'تتبع الطرود',
    'homepage.services.1.description': 'تتبع شحناتك في الوقت الفعلي',
    'homepage.services.2.title': 'تعامل آمن',
    'homepage.services.2.description': 'يتم التعامل مع طرودك دائمًا بعناية',
    'homepage.howItWorks.0.title': 'إنشاء طلب',
    'homepage.howItWorks.0.description': 'املأ تفاصيل الشحن',
    'homepage.howItWorks.1.title': 'جدولة الاستلام',
    'homepage.howItWorks.1.description': 'سنقوم بجمع الطرد الخاص بك',
    'homepage.howItWorks.2.title': 'تتبع التوصيل',
    'homepage.howItWorks.2.description': 'مراقبة شحنتك في الوقت الفعلي',
    'homepage.cta.title': 'جاهز للشحن؟',
    'homepage.cta.subtitle': 'اشترك الآن وأرسل طردك الأول اليوم',
    'homepage.cta.buttonText': 'ابدأ الآن',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'تسجيل',
    'auth.forgotPassword': 'نسيت كلمة المرور',
    'auth.email': 'البريد الإلكتروني',
    'auth.identifier': 'البريد الإلكتروني أو الهاتف',
    'auth.identifierPlaceholder': 'أدخل البريد الإلكتروني أو رقم الهاتف',
    'auth.identifierHelp': 'يمكنك تسجيل الدخول إما باستخدام عنوان بريدك الإلكتروني أو رقم الهاتف',
    'auth.password': 'كلمة المرور',
    'auth.rememberMe': 'تذكرني',
    'auth.dontHaveAccount': 'ليس لديك حساب؟',
    'auth.registerHere': 'سجل هنا',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.phone': 'الهاتف',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'auth.confirmPasswordPlaceholder': 'تأكيد كلمة المرور',
    'auth.registerAsDriver': 'التسجيل كسائق',
    'auth.accountInformation': 'معلومات الحساب',
    'auth.firstNamePlaceholder': 'أدخل الاسم الأول',
    'auth.lastNamePlaceholder': 'أدخل اسم العائلة',
    'auth.phonePlaceholder': 'أدخل رقم الهاتف',
    'auth.passwordPlaceholder': 'أنشئ كلمة مرور',
    'auth.alreadyHaveAccount': 'هل لديك حساب بالفعل؟',
    'auth.loginHere': 'تسجيل الدخول هنا',
    'auth.registerAsCustomer': 'هل تريد التسجيل كعميل؟',
    'auth.completeRegistration': 'إكمال التسجيل',
    'auth.registering': 'جاري التسجيل...',
    'auth.fillAllFields': 'يرجى ملء جميع الحقول المطلوبة',
    'auth.passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
    'auth.registrationFailed': 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    
    // Admin
    'admin.title': 'المسؤول',
    'admin.client': 'عميل',
    'admin.driver': 'سائق',
    'admin.allOrders': 'جميع الطلبات',
    'admin.manageUsers': 'إدارة المستخدمين',
    'admin.driverApprovals': 'موافقات السائقين',
    'admin.paymentManagement': 'إدارة المدفوعات',
    'admin.orderManagement': 'إدارة الطلبات',
    'admin.searchOrders': 'البحث بواسطة رقم الطلب أو العميل أو العنوان',
    'admin.search': 'بحث',
    'admin.allStatuses': 'جميع الحالات',
    'admin.refresh': 'تحديث',
    'admin.orderNumber': 'رقم الطلب',
    'admin.customer': 'العميل',
    'admin.status': 'الحالة',
    'admin.pickupAddress': 'عنوان الاستلام',
    'admin.deliveryAddress': 'عنوان التسليم',
    'admin.created': 'تاريخ الإنشاء',
    'admin.amount': 'المبلغ',
    'admin.actions': 'الإجراءات',
    'admin.details': 'التفاصيل',
    'admin.portal': 'بوابة المسؤول',
    'admin.adminBadge': 'مسؤول',
    'admin.dashboard': 'لوحة تحكم المسؤول',
    'admin.drivers': 'السائقين',
    'admin.customers': 'العملاء',
    'admin.settings': 'الإعدادات',
    'admin.noPermission': 'ليس لديك إذن للوصول إلى هذه الصفحة.',
    'admin.searchDrivers': 'البحث بواسطة الاسم أو البريد الإلكتروني',
    'admin.approved': 'موافق',
    'admin.rejected': 'مرفوض',
    'admin.view': 'عرض',
    'admin.approve': 'موافق',
    'admin.reject': 'مرفوض',
    'admin.noDriverApplications': 'لم يتم العثور على طلبات السائقين',
    'admin.approveDriver': 'موافق السائق',
    'admin.rejectDriver': 'مرفوض السائق',
    'admin.confirmApproveDriver': 'هل أنت متأكد أنك تريد موافقة الطلب على السائق',
    'admin.confirmRejectDriver': 'هل أنت متأكد أنك تريد مرفضة الطلب على السائق',
    'admin.rejectionReason': 'سبب الرفض',
    'admin.rejectionReasonPlaceholder': 'يرجى تقديم سبب الرفض...',
    'admin.driverId': 'رقم السائق',
    
    // Users management page
    'admin.users.manageUsers': 'إدارة المستخدمين',
    'admin.users.searchPlaceholder': 'البحث باستخدام الاسم أو البريد الإلكتروني',
    'admin.users.allRoles': 'جميع الأدوار',
    'admin.users.roleAdmin': 'المسؤولون',
    'admin.users.roleClient': 'العملاء',
    'admin.users.roleDriver': 'السائقون',
    'admin.users.roleADMIN': 'المسؤول',
    'admin.users.roleCLIENT': 'العميل',
    'admin.users.roleDRIVER': 'السائق',
    'admin.users.active': 'نشط',
    'admin.users.inactive': 'غير نشط',
    'admin.users.never': 'أبدًا',
    'admin.users.name': 'الاسم',
    'admin.users.email': 'البريد الإلكتروني',
    'admin.users.role': 'الدور',
    'admin.users.status': 'الحالة',
    'admin.users.joined': 'تاريخ الانضمام',
    'admin.users.lastActive': 'آخر نشاط',
    'admin.users.resetPwd': 'إعادة تعيين كلمة المرور',
    'admin.users.deactivate': 'تعطيل',
    'admin.users.activate': 'تفعيل',
    'admin.users.noUsersFound': 'لم يتم العثور على مستخدمين مطابقين لمعاييرك',
    'admin.users.userDetails': 'تفاصيل المستخدم',
    'admin.users.basicInfo': 'المعلومات الأساسية',
    'admin.users.accountDetails': 'تفاصيل الحساب',
    'admin.users.driverProfile': 'ملف السائق',
    'admin.users.driverInfo': 'معلومات السائق',
    'admin.users.phone': 'الهاتف',
    'admin.users.notProvided': 'غير مقدم',
    'admin.users.totalOrders': 'إجمالي الطلبات',
    'admin.users.documents': 'المستندات',
    'admin.users.clickToEnlarge': 'اضغط لتكبير',
    'admin.users.viewFullSize': 'عرض الحجم الكامل',
    'admin.users.noDocumentsAvailable': 'لا توجد مستندات متاحة',
    'admin.users.noDriverProfileInfo': 'لا توجد معلومات ملف السائق',
    'admin.users.resetPassword': 'إعادة تعيين كلمة المرور',
    'admin.users.resetPasswordConfirm': 'هل أنت متأكد أنك تريد إعادة تعيين كلمة المرور ل',
    'admin.users.resetPasswordWarning': 'سيتم إنشاء كلمة مرور مؤقتة وإظهارها هنا',
    'admin.users.confirmReset': 'إعادة تعيين كلمة المرور',
    'admin.users.noEmailError': 'لم يتم إدخال عنوان بريد إلكتروني',
    'admin.users.passwordResetSuccess': 'تم إعادة تعيين كلمة المرور بنجاح',
    'admin.users.passwordResetFailed': 'فشل إعادة تعيين كلمة المرور',
    'admin.users.tempPassword': 'كلمة مرور مؤقتة',
    'admin.users.passwordWarning': 'شارك هذه كلمة المرور المؤقتة مع المستخدم بأمان',
    'admin.users.approvalStatus': 'حالة الموافقة',
    'admin.users.pending': 'قيد الانتظار',
    'admin.users.editUser': 'تعديل المستخدم',
    'admin.edit': 'تعديل',
    'admin.users.editInfo': 'تعديل المعلومات الشخصية',
    'admin.users.addressInfo': 'معلومات العنوان',
    'admin.users.streetAddress': 'عنوان الشارع',
    'admin.users.city': 'المدينة',
    'admin.users.state': 'المحافظة',
    'admin.users.zipCode': 'الرمز البريدي',
    'admin.users.country': 'البلد',
    'admin.users.saveChanges': 'حفظ التغييرات',
    'admin.users.userUpdated': 'تم تحديث معلومات المستخدم بنجاح',
    'admin.users.updateFailed': 'فشل في تحديث معلومات المستخدم',
    'admin.users.fieldRequired': 'هذا الحقل مطلوب',
    
    // Driver
    'driver.becomeDriver': 'هل تريد أن تصبح سائقًا؟',
    'driver.earnMoney': 'اكسب المال عن طريق توصيل الطرود',
    'driver.registration': 'تسجيل السائق',
    'driver.vehicle': 'المركبة',
    'driver.applicationDate': 'تاريخ التقديم',
    'driver.applicationDetails': 'تفاصيل طلب السائق',
    'driver.personalInfo': 'المعلومات الشخصية',
    'driver.vehicleInfo': 'معلومات المركبة',
    'driver.make': 'الصنع',
    'driver.model': 'الموديل',
    'driver.year': 'السنة',
    'driver.color': 'اللون',
    'driver.licensePlate': 'لوحة الترخيص',
    'driver.licenseInfo': 'معلومات الرخصة',
    'driver.licenseNumber': 'رقم الرخصة',
    'driver.expiryDate': 'تاريخ الانتهاء',
    'driver.documents': 'المستندات',
    'driver.license': 'رخصة القيادة',
    'driver.vehicleRegistration': 'تسجيل المركبة',
    'driver.insurance': 'التأمين',
    'driver.backgroundCheck': 'التحقق من الخلفية',
    'driver.noDocuments': 'لا توجد مستندات متاحة',
    'driver.driverPhotos': 'صور السائق (صورة شخصية)',
    'driver.carPhotos': 'صور السيارة',
    'driver.uploadDriverPhoto': 'تحميل صورة السائق',
    'driver.uploadCarPhotos': 'تحميل صور السيارة',
    'driver.uploadLicense': 'تحميل الرخصة',
    'driver.photos': 'صور',
    'driver.photoInstructions': 'يرجى تقديم صورة واضحة لوجهك (مثل صورة شخصية) مع إضاءة جيدة.',
    'driver.carPhotoInstructions': 'يرجى تقديم صور لسيارتك من زوايا مختلفة (الأمام والخلف والجوانب).',
    'driver.licenseInstructions': 'يرجى تقديم صورة واضحة أو مسح ضوئي لرخصة القيادة الصالحة الخاصة بك.',
    'driver.uploadingDocuments': 'جاري تحميل المستندات...',
    'driver.maxDriverPhotosError': 'يُسمح بحد أقصى صورتين للسائق',
    'driver.maxCarPhotosError': 'يُسمح بحد أقصى 4 صور للسيارة',
    'driver.plateNumberRequired': 'رقم لوحة الترخيص مطلوب',
    'driver.licenseRequired': 'نسخة من رخصة القيادة مطلوبة',
    'driver.carPhotoRequired': 'مطلوب صورة واحدة على الأقل للسيارة',
    'driver.driverPhotoRequired': 'مطلوب صورة واحدة على الأقل للسائق',
    'driver.uploadLicenseError': 'فشل في تحميل وثيقة الترخيص',
    'driver.uploadCarPhotoError': 'فشل في تحميل صورة السيارة',
    'driver.uploadDriverPhotoError': 'فشل في تحميل صورة السائق',
    'driver.uploadInsuranceError': 'فشل في تحميل وثيقة التأمين',
    'driver.uploadError': 'فشل في تحميل المستندات. يرجى المحاولة مرة أخرى.',
    'driver.licensePlatePlaceholder': 'أدخل رقم لوحة الترخيص',
    'driver.makePlaceholder': 'مثال: تويوتا، هوندا',
    'driver.modelPlaceholder': 'مثال: كامري، سيفيك',
    'driver.yearPlaceholder': 'مثال: 2020',
    'driver.colorPlaceholder': 'مثال: أسود، أبيض',
    
    // Admin payments
    'admin.payments.totalCommission': 'إجمالي العمولة',
    'admin.payments.pendingCommission': 'العمولة المعلقة',
    'admin.payments.rejectedPayments': 'المدفوعات المرفوضة',
    'admin.payments.totalDrivers': 'إجمالي السائقين',
    'admin.payments.topDriversByCommission': 'أفضل السائقين حسب العمولة المدفوعة',
    'admin.payments.driver': 'السائق',
    'admin.payments.paidCommission': 'العمولة المدفوعة',
    'admin.payments.totalPayments': 'إجمالي المدفوعات',
    'admin.payments.noDriverData': 'لا توجد بيانات دفع متاحة',
    'admin.payments.paymentsTab': 'إدارة المدفوعات',
    'admin.payments.bankAccountsTab': 'الحسابات المصرفية',
    'admin.payments.paymentId': 'معرف الدفع',
    'admin.payments.amount': 'المبلغ',
    'admin.payments.status': 'الحالة',
    'admin.payments.date': 'التاريخ',
    'admin.payments.actions': 'الإجراءات',
    'admin.payments.confirmed': 'مؤكد',
    'admin.payments.pending': 'قيد الانتظار',
    'admin.payments.rejected': 'مرفوض',
    'admin.payments.confirm': 'تأكيد',
    'admin.payments.reject': 'رفض',
    'admin.payments.unknownDriver': 'سائق غير معروف',
    'admin.payments.noPaymentsFound': 'لم يتم العثور على مدفوعات',
    'admin.payments.management': 'إدارة المدفوعات',
    'admin.payments.totalPending': 'إجمالي المعلق',
    'admin.payments.totalConfirmed': 'إجمالي المؤكد',
    'admin.payments.totalRejected': 'إجمالي المرفوض',
    'admin.payments.reportedIssues': 'المشكلات المبلغ عنها',
    'admin.payments.requiresAttention': 'تتطلب انتباه',
    'admin.payments.payments': 'مدفوعات',
    'admin.payments.addBankAccount': 'إضافة حساب مصرفي',
    'admin.payments.noPendingPayments': 'لا توجد مدفوعات معلقة',
    'admin.payments.bankAccount': 'الحساب المصرفي',
    'admin.payments.noBankAccount': 'لا يوجد حساب مصرفي',
    'admin.payments.noConfirmedPayments': 'لا توجد مدفوعات مؤكدة',
    'admin.payments.confirmedBy': 'تم التأكيد بواسطة',
    'admin.system': 'النظام',
    'admin.payments.noRejectedPayments': 'لا توجد مدفوعات مرفوضة',
    'admin.payments.rejectionReason': 'سبب الرفض',
    'admin.payments.noReasonProvided': 'لم يتم تقديم سبب',
    'admin.payments.rejectedBy': 'تم الرفض بواسطة',
    'admin.payments.issues': 'المشكلات',
    'admin.payments.noReportedIssues': 'لا توجد مشكلات مبلغ عنها',
    'admin.payments.issue': 'المشكلة',
    'admin.payments.issueReported': 'تم الإبلاغ عن مشكلة',
    'admin.payments.bankAccounts': 'الحسابات المصرفية',
    'admin.payments.noBankAccounts': 'لا توجد حسابات مصرفية',
    'admin.payments.bankName': 'اسم البنك',
    'admin.payments.accountName': 'اسم الحساب',
    'admin.payments.accountNumber': 'رقم الحساب',
    'admin.payments.sortCode': 'رمز الفرز',
    'admin.payments.description': 'الوصف',
    'admin.payments.active': 'نشط',
    'admin.payments.inactive': 'غير نشط',
    'admin.payments.paymentDetails': 'تفاصيل الدفع',
    'admin.payments.paymentInfo': 'معلومات الدفع',
    'admin.payments.id': 'المعرف',
    'admin.payments.notes': 'ملاحظات',
    'admin.payments.driverInfo': 'معلومات السائق',
    'admin.payments.name': 'الاسم',
    'admin.payments.email': 'البريد الإلكتروني',
    'admin.payments.phone': 'الهاتف',
    'admin.notProvided': 'غير مقدم',
    'admin.payments.driverNotFound': 'لم يتم العثور على السائق',
    'admin.payments.bankAccountInfo': 'معلومات الحساب المصرفي',
    'admin.payments.noBankAccountLinked': 'لا يوجد حساب مصرفي مرتبط',
    'admin.payments.paymentActions': 'إجراءات الدفع',
    'admin.payments.confirmPayment': 'تأكيد الدفع',
    'admin.payments.rejectPayment': 'رفض الدفع',
    'admin.payments.rejectionReasonPlaceholder': 'أدخل سبب الرفض',
    'admin.payments.rejectionNoteRequired': 'ملاحظة الرفض مطلوبة',
    'admin.payments.paymentReceipt': 'إيصال الدفع',
    'admin.payments.editBankAccount': 'تعديل الحساب المصرفي',
    'admin.payments.isActive': 'نشط',
    'admin.payments.defaultRejectionNote': 'تم رفض الدفع من قبل المسؤول',
    'admin.payments.bankSaveError': 'فشل حفظ الحساب المصرفي',
    'admin.payments.confirmDeleteBank': 'هل أنت متأكد أنك تريد حذف هذا الحساب المصرفي؟',
    'admin.payments.bankDeleteError': 'فشل حذف الحساب المصرفي',
    
    // General
    'general.notApplicable': 'غير مطبق',
    'general.clickToEnlarge': 'اضغط لتكبير',
    'general.viewFullSize': 'عرض الحجم الكامل',
    'general.currency': 'ريال سعودي',
    
    // Orders
    'orders.title': 'طلباتي',
    'orders.new': 'إنشاء طلب جديد',
    'orders.track': 'تتبع الطلب',
    'orders.details': 'تفاصيل الطلب',
    'orders.available': 'الطلبات المتاحة',
    'orders.current': 'الطلبات الحالية',
    'orders.history': 'سجل الطلبات',
    'orders.viewCurrentOrders': 'عرض الطلبات الحالية',
    'orders.haveActiveOrder': 'لديك طلب نشط',
    'orders.oneOrderAtTime': 'يمكنك قبول طلب واحد فقط في المرة الواحدة. يرجى إكمال أو إلغاء طلبك الحالي قبل قبول طلب جديد.',
    'orders.lookingToAccept': 'تبحث عن طلبات للقبول؟',
    'orders.pendingDescription': 'جميع الطلبات ذات حالة قيد الانتظار معروضة هنا. بمجرد قبول الطلب، سيظهر في الطلبات الحالية الخاصة بك.',
    'orders.orderInfo': 'معلومات الطلب',
    'orders.created': 'تاريخ الإنشاء',
    'orders.updated': 'تاريخ التحديث',
    'orders.estimatedDelivery': 'وقت التسليم المتوقع',
    'orders.yes': 'نعم',
    'orders.no': 'لا',
    'orders.viewOnMap': 'عرض على الخريطة',
    'orders.client': 'العميل',
    'orders.driver': 'السائق',
    'orders.name': 'الاسم',
    'orders.email': 'البريد الإلكتروني',
    'orders.phone': 'الهاتف',
    'orders.noDriverAssigned': 'لم يتم تعيين سائق بعد',
    'orders.error': 'خطأ!',
    'orders.retry': 'إعادة المحاولة',
    'orders.notFound': 'الطلب غير موجود',
    'orders.noPermission': 'لم يتم العثور على الطلب المطلوب أو ليس لديك إذن لعرضه.',
    'orders.missingOrderId': 'رقم الطلب مفقود',
    'orders.fetchDetailsFailed': 'فشل في جلب تفاصيل الطلب',
    'orders.acceptSuccess': 'تم قبول الطلب بنجاح',
    'orders.acceptFailed': 'فشل في قبول الطلب',
    'orders.pickedUpSuccess': 'تم تحديد الطلب كمستلم',
    'orders.deliveredSuccess': 'تم تحديد الطلب كمسلم',
    'orders.updateStatusFailed': 'فشل في تحديث حالة الطلب',
    'orders.cancelSuccess': 'تم إلغاء الطلب بنجاح',
    'orders.country': 'الدولة',
    'orders.loadingAvailable': 'جاري تحميل الطلبات المتاحة...',
    'orders.noAvailable': 'لا توجد طلبات متاحة',
    'orders.checkBackLater': 'لا توجد حاليًا طلبات متاحة للقبول. يرجى التحقق مرة أخرى لاحقًا.',
    'orders.orderNumber': 'الطلب رقم',
    'orders.acceptOrder': 'قبول الطلب',
    'orders.acceptingOrder': 'جاري القبول...',
    'orders.weightUnit': 'رطل',
    'orders.distanceUnit': 'ميل',
    'orders.distance': 'المسافة',
    'orders.timeUnit': 'دقيقة',
    'orders.estimatedTime': 'الوقت المقدر',
    'orders.fragileWarning': 'قابل للكسر - تعامل بحذر',
    'orders.noActiveOrders': 'لا توجد طلبات نشطة',
    'orders.noDriverOrders': 'ليس لديك أي طلبات مسندة في الوقت الحالي. تحقق من صفحة الطلبات المتاحة لقبول طلبات جديدة.',
    'orders.noClientOrders': 'ليس لديك أي طلبات نشطة في الوقت الحالي.',
    'orders.findAvailable': 'البحث عن الطلبات المتاحة',
    'orders.refreshing': 'جاري التحديث...',
    'orders.trackingNumber': 'رقم التتبع',
    'orders.status': 'الحالة',
    'orders.actions': 'الإجراءات',
    'orders.price': 'السعر',
    'orders.createdAt': 'تاريخ الإنشاء',
    'orders.completedDate': 'تاريخ الإكمال',
    'orders.noCompletedOrders': 'لا توجد طلبات مكتملة',
    'orders.noOrdersInHistory': 'ليس لديك أي طلبات مكتملة في سجلك.',
    'orders.markAsPickedUp': 'تحديد كمستلم',
    'orders.startTransit': 'بدء النقل',
    'orders.markAsDelivered': 'تحديد كمسلم',
    'orders.cancelOrder': 'إلغاء الطلب',
    'orders.confirmClientCancel': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.',
    'orders.confirmDriverCancel': 'هل أنت متأكد أنك تريد إلغاء هذا التوصيل؟ سيجعل هذا الطلب متاحًا للسائقين الآخرين.',
    'orders.confirmAdminCancel': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.',
    'orders.clientCancelSuccess': 'تم إلغاء الطلب بنجاح',
    'orders.driverCancelSuccess': 'تم إلغاء التوصيل بنجاح',
    'orders.adminCancelSuccess': 'تم إلغاء الطلب بنجاح',
    'orders.cancelFailed': 'فشل إلغاء الطلب',
    'orders.cancelError': 'فشل إلغاء الطلب. يرجى المحاولة مرة أخرى.',
    
    // Payments
    'payment.history': 'سجل المدفوعات',
    'payment.history.loading': 'جاري تحميل سجل المدفوعات...',
    'payment.history.noHistory': 'لا يوجد سجل مدفوعات',
    'payment.history.noRecords': 'ليس لديك أي سجلات دفع حتى الآن.',
    'payment.history.viewReceipt': 'عرض الإيصال',
    'payment.confirmation': 'تأكيد الدفع',
    'payment.confirmation.bankAccounts': 'الحسابات المصرفية',
    'payment.confirmation.noBankAccounts': 'لا توجد حسابات مصرفية متاحة. يرجى الاتصال بالمسؤول.',
    'payment.confirmation.pendingPayments': 'المدفوعات المعلقة',
    'payment.confirmation.loadingPayments': 'جاري تحميل المدفوعات...',
    'payment.confirmation.noPendingPayments': 'لا توجد مدفوعات معلقة',
    'payment.confirmation.noPaymentsDescription': 'لا توجد حاليا مدفوعات تحتاج إلى تأكيد.',
    'payment.confirmation.order': 'الطلب',
    'payment.confirmation.method': 'طريقة الدفع',
    'payment.confirmation.reference': 'المرجع',
    'payment.confirmation.receipt': 'إيصال',
    'payment.confirmation.ref': 'مرجع',
    'payment.confirmation.verifyMessage': 'يرجى تأكيد أن هذا الدفع تمت معالجته بشكل صحيح أو الإبلاغ عن مشكلة إذا كانت هناك مشكلة.',
    'payment.confirmation.reportIssue': 'الإبلاغ عن مشكلة',
    'payment.confirmation.confirm': 'تأكيد الدفع',
    'payment.confirmation.success': 'تم تأكيد الدفع بنجاح!',
    'payment.confirmation.failed': 'فشل تأكيد الدفع. يرجى المحاولة مرة أخرى.',
    'payment.confirmation.reportedIssue': 'تم الإبلاغ عن مشكلة من قبل السائق',
    'payment.confirmation.reportFailed': 'فشل الإبلاغ عن مشكلة الدفع. يرجى المحاولة مرة أخرى.',
    'payment.confirmation.issueReported': 'تم إبلاغ المسؤول عن مشكلة الدفع',
    'button.processing': 'جاري المعالجة...',
    
    // User
    'user.profile': 'الملف الشخصي',
    'user.notifications': 'الإشعارات',
    
    // Notifications page
    'notifications.title': 'إشعاراتك',
    'notifications.refresh': 'تحديث',
    'notifications.markSelected': 'تحديد المحدد كمقروء',
    'notifications.filter': 'تصفية:',
    'notifications.all': 'الكل',
    'notifications.unread': 'غير مقروء',
    'notifications.read': 'مقروء',
    'notifications.type': 'النوع:',
    'notifications.empty': 'لم يتم العثور على إشعارات مطابقة لعوامل التصفية.',
    'notifications.loading': 'جاري التحميل...',
    'notifications.showing': 'عرض {0} إشعار(ات)',
    'notifications.select': 'تحديد',
    'notifications.time': 'الوقت',
    'notifications.details': 'التفاصيل',
    'notifications': 'الإشعارات',
    'noNotifications': 'لم يوجد إشعارات',
    
    // Notification types and common messages
    'notification.order.assigned': 'لقد تم تعيينك إلى طلب #{0}',
    'notification.order.delivered': 'تم تسليم طلب #{0}',
    'notification.order.cancelled': 'تم إلغاء طلب #{0}',
    'notification.order.status_update.title': 'تم تحديث حالة الطلب',
    'notification.order.status_update.accepted': 'قام السائق {0} بقبول طلبك رقم #{1}',
    'notification.order.status_update.picked_up': 'قام السائق {0} باستلام طلبك رقم #{1}',
    'notification.order.status_update.in_transit': 'طلبك رقم #{0} قيد النقل الآن',
    'notification.payment.received': 'تم استلام دفعة بقيمة {0} ريال سعودي',
    'notification.payment.confirmed': 'تم تأكيد دفعتك لطلب #{0}',
    'notification.payment.rejected': 'تم رفض دفعتك لطلب #{0}',
    'notification.account.welcome': 'مرحبا بك في Katakksa! تم إنشاء حسابك بنجاح بنجاح.',
    'notification.system.maintenance': 'تم إجراء صيانة النظام المجدولة لـ {0}',
    
    // Buttons
    'button.submit': 'إرسال',
    'button.cancel': 'إلغاء',
    'button.save': 'حفظ',
    'button.update': 'تحديث',
    'button.loading': 'جاري التحميل...',
    'button.close': 'إغلاق',
    'button.next': 'التالي',
    'button.back': 'رجوع',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً',
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcomeMessage': 'مرحباً',
    'dashboard.summary': 'يمكنك عرض إحصائيات طلباتك والأنشطة الأخيرة هنا.',
    'dashboard.user': 'المستخدم',
    'dashboard.totalOrders': 'إجمالي الطلبات',
    'dashboard.activeOrders': 'الطلبات النشطة',
    'dashboard.completedOrders': 'الطلبات المكتملة',
    'dashboard.cancelledOrders': 'الطلبات الملغاة',
    'dashboard.pendingOrders': 'الطلبات المعلقة',
    'dashboard.inTransit': 'قيد النقل',
    'dashboard.delivered': 'تم التوصيل',
    'dashboard.recentOrders': 'الطلبات الأخيرة',
    'dashboard.noRecentOrders': 'لم يتم العثور على طلبات حديثة',
    'dashboard.noOrders': 'لم يتم العثور على طلبات',
    'dashboard.trackingNumber': 'رقم التتبع',
    'dashboard.orderID': 'رقم الطلب',
    'dashboard.date': 'التاريخ',
    'dashboard.status': 'الحالة',
    'dashboard.destination': 'الوجهة',
    'dashboard.createdAt': 'تاريخ الإنشاء',
    'dashboard.actions': 'الإجراءات',
    'dashboard.viewDetails': 'عرض التفاصيل',
    'dashboard.orderStatus.PENDING': 'قيد الانتظار',
    'dashboard.orderStatus.IN_TRANSIT': 'قيد النقل',
    'dashboard.orderStatus.DELIVERED': 'تم التوصيل',
    'dashboard.orderStatus.CANCELLED': 'ملغي',
    'dashboard.orderStatus.ACCEPTED': 'مقبول',
    'dashboard.orderStatus.PICKED_UP': 'تم الاستلام',
    
    // Profile
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.saving': 'جاري الحفظ...',
    'profile.updateSuccess': 'تم تحديث الملف الشخصي بنجاح',
    
    // Order Form
    'orders.fillPickupFields': 'يرجى ملء جميع حقول عنوان الاستلام المطلوبة',
    'orders.fillDeliveryFields': 'يرجى ملء جميع حقول عنوان التسليم المطلوبة بما في ذلك رقم هاتف المستلم',
    'orders.invalidMobile': 'يرجى إدخال رقم هاتف صحيح للمستلم',
    'orders.fillPackageDetails': 'يرجى ملء وزن الطرد والسعر',
    'orders.invalidPrice': 'يرجى إدخال سعر صحيح أكبر من صفر',
    'orders.pickup': 'الاستلام',
    'orders.delivery': 'التوصيل',
    'orders.package': 'الطرد',
    'orders.location': 'الموقع',
    'orders.pickupAddress': 'عنوان الاستلام',
    'orders.deliveryAddress': 'عنوان التوصيل',
    'orders.street': 'الشارع',
    'orders.city': 'المدينة',
    'orders.state': 'المحافظة',
    'orders.recipientMobile': 'رقم هاتف المستلم',
    'orders.packageDetails': 'تفاصيل الطرد والسعر',
    'orders.weight': 'وزن الطرد (رطل)',
    'orders.dimensions': 'الأبعاد (طول×عرض×ارتفاع بالإنش)',
    'orders.description': 'وصف الطرد',
    'orders.fragile': 'هذا الطرد قابل للكسر',
    'orders.enterPrice': 'أدخل السعر',
    'orders.deliveryLocation': 'موقع التسليم',
    'orders.selectLocation': 'الرجاء تحديد موقع التسليم بالضبط على الخريطة',
    'orders.mapPlaceholder': 'سيتم عرض الخريطة هنا',
    'orders.mapIntegration': '(مطلوب تكامل مع خرائط جوجل أو خدمة مماثلة)',
    'orders.selectedLocation': 'الموقع المحدد',
    'orders.noLocationSelectedYet': 'لم يتم تحديد موقع بعد',
    'orders.useDeliveryAddress': 'استخدم عنوان التسليم',
    'orders.simulateMapSelection': 'محاكاة تحديد الخريطة',
    'orders.note': 'ملاحظة',
    'orders.realImplementation': 'في التطبيق الفعلي، سيتم استبدال هذا بخريطة تفاعلية حيث يمكن للمستخدمين تحديد موقع التسليم بدقة.',
    'orders.newOrderDescription': 'املأ النموذج لإنشاء طلب شحن جديد',
    'orders.creating': 'جاري إنشاء الطلب...',
    'orders.createOrder': 'إنشاء طلب',
    'orders.createNewOrder': 'إنشاء طلب جديد',
    'orders.processing': 'جاري المعالجة...',
    'orders.next': 'التالي',
    'orders.previous': 'السابق',
    
    // Pagination
    'pagination.previous': 'السابق',
    'pagination.next': 'التالي',
    'pagination.noOrders': 'لم يتم العثور على طلبات مطابقة لمعاييرك',
    
    // Admin Dashboard
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.activeUsers': 'نشط',
    'admin.totalOrdersCount': 'إجمالي الطلبات',
    'admin.totalCompleted': 'مكتمل',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.revenueGrowth': 'نمو',
    'admin.pendingDriversCount': 'السائقين المعلقين',
    'admin.awaitingApproval': 'في انتظار الموافقة',
    'admin.viewAllUsers': 'عرض جميع المستخدمين',
    'admin.viewAllOrders': 'عرض جميع الطلبات',
    'admin.revenueDetails': 'تفاصيل الإيرادات',
    'admin.viewPendingDrivers': 'عرض السائقين المعلقين',
    'admin.recentOrdersList': 'الطلبات الأخيرة',
    'admin.recentUsers': 'المستخدمين الأخيرين',
    'admin.noRecentOrders': 'لم يتم العثور على طلبات حديثة',
    'admin.noRecentUsers': 'لم يتم العثور على مستخدمين حديثين',
    'admin.orderNum': 'رقم الطلب',
    'admin.customerName': 'العميل',
    'admin.dateField': 'التاريخ',
    'admin.statusField': 'الحالة',
    'admin.amountField': 'المبلغ',
    'admin.nameField': 'الاسم',
    'admin.emailField': 'البريد الإلكتروني',
    'admin.roleField': 'الدور',
    'admin.joinedDate': 'تاريخ الانضمام',
    'admin.lastActive': 'آخر نشاط',
    'admin.viewAll': 'عرض الكل',
    'admin.never': 'أبدًا',
    
    // Logout
    'logout.confirmMessage': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    
    // Common Loading and Error Messages
    'loading.message': 'جاري التحميل...',
    'error.failed': 'فشل تحميل البيانات. يرجى المحاولة مرة أخرى.',
    'error.auth': 'بيانات المستخدم غير مكتملة. يرجى تسجيل الدخول مرة أخرى.',
    'button.search': 'بحث',
    'button.clear': 'مسح',
    'button.filter': 'تصفية',
    'button.resetFilters': 'إعادة ضبط التصفية',
    'button.delete': 'حذف',
    'button.confirm': 'تأكيد',
    'button.reject': 'رفض',
    'button.approve': 'موافقة',
    'button.previous': 'السابق',
    'button.refresh': 'تحديث',
    
    // Driver
    'driver.verificationPending': 'التحقق قيد الانتظار',
    'driver.verificationPendingMessage': 'شكراً لتسجيلك كسائق على منصتنا. تم تقديم طلبك وهو الآن قيد التحقق.',
    'driver.verificationReviewMessage': 'سيقوم فريق الإدارة لدينا بمراجعة معلوماتك ومستنداتك. عادة ما يستغرق ذلك من 1 إلى 3 أيام عمل. ستتلقى إشعاراً بالبريد الإلكتروني بمجرد الموافقة على حسابك أو إذا كنا بحاجة إلى معلومات إضافية.',
    'driver.whatsNext': 'ماذا سيحدث بعد ذلك؟',
    'driver.nextStep1': 'ستتم مراجعة تسجيلك كسائق من قبل فريق الإدارة لدينا',
    'driver.nextStep2': 'قد نتصل بك للحصول على معلومات إضافية إذا لزم الأمر',
    'driver.nextStep3': 'بمجرد الموافقة، ستتلقى بريدًا إلكترونيًا يحتوي على تفاصيل حسابك',
    'driver.nextStep4': 'يمكنك بعد ذلك تسجيل الدخول والبدء في قبول مهام التوصيل',
    'driver.goToLogin': 'الذهاب إلى صفحة تسجيل الدخول',
    'driver.returnToHome': 'العودة إلى الصفحة الرئيسية',
    'driver.needHelp': 'هل تحتاج إلى مساعدة؟',
    'driver.contactSupport': 'اتصل بالدعم',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const [translations, setTranslations] = useState<Translations>(defaultTranslations);
  
  // Initialize language from localStorage on mount
  useEffect(() => {
    try {
      const savedLanguage = localStorage.getItem('app_language');
      if (savedLanguage === 'ar' || savedLanguage === 'en') {
        setLanguage(savedLanguage);
      }
    } catch (error) {
      console.error('Error reading language from localStorage:', error);
    }
  }, []);
  
  // Update HTML attributes and localStorage when language changes
  useEffect(() => {
    try {
      // Update localStorage
      localStorage.setItem('app_language', language);
      
      // Update HTML attributes
      document.documentElement.lang = language;
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      
      // Update body classes for font
      if (language === 'ar') {
        document.body.classList.add('font-tajawal');
      } else {
        document.body.classList.remove('font-tajawal');
      }
    } catch (error) {
      console.error('Error updating language attributes:', error);
    }
  }, [language]);
  
  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
  };
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: changeLanguage, 
      t,
      translations
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 